Add Kerberos support for JDBC
exasol/tableau-connector pull request #29
Opened 2021-10-28 15:03 UTC by kaklakariada

Closes #15

2021-11-08 12:54 UTC, kaklakariada commented
# Test reports
## JDBC TDVT
```
$ python -m tdvt.tdvt run exasol_jdbc
Setting tdvt thread count to: 6
Testing exasol_jdbc
thread setting in exasol_jdbc.ini = 1
Starting smoke tests. Creating 1 worker threads.

Running exasol_jdbc StaplesConnectionTestexasol_jdbc 11

.
Finished exasol_jdbc StaplesConnectionTestexasol_jdbc 11

Running exasol_jdbc CastCalcsConnectionTestexasol_jdbc 11

.
Finished exasol_jdbc CastCalcsConnectionTestexasol_jdbc 11

2 smoke test(s) ran. 0 smoke tests disabled.
Smoke tests ran in 13.89 seconds.

Starting tests. Creating 1 worker threads.
Running exasol_jdbc logical.calcs.exasol_jdbc 1

...............................
Finished exasol_jdbc logical.calcs.exasol_jdbc 1

Running exasol_jdbc logical.staples.exasol_jdbc 2

..........................................
Finished exasol_jdbc logical.staples.exasol_jdbc 2

Running exasol_jdbc logical.lod.exasol_jdbc 3

...........................
Finished exasol_jdbc logical.lod.exasol_jdbc 3

Running exasol_jdbc logical.union.exasol_jdbc 4

.
Finished exasol_jdbc logical.union.exasol_jdbc 4

Running exasol_jdbc expression.standard.exasol_jdbc 5

...............................................................................................................................................................................................................
Finished exasol_jdbc expression.standard.exasol_jdbc 5

Running exasol_jdbc expression.lod.exasol_jdbc 6

.
Finished exasol_jdbc expression.lod.exasol_jdbc 6

Running exasol_jdbc expression.staples.exasol_jdbc 7

....
Finished exasol_jdbc expression.staples.exasol_jdbc 7

Running exasol_jdbc expression.median.exasol_jdbc 8

.
Finished exasol_jdbc expression.median.exasol_jdbc 8

Running exasol_jdbc expression.percentile.exasol_jdbc 9

.
Finished exasol_jdbc expression.percentile.exasol_jdbc 9

Running exasol_jdbc calc_data.exasol_jdbc 10

.
Finished exasol_jdbc calc_data.exasol_jdbc 10

Running exasol_jdbc TestBadPassword.exasol_jdbc 11

.
Finished exasol_jdbc TestBadPassword.exasol_jdbc 11


Test Count: 921 tests
        Passed tests: 921
        Failed tests: 0
        Tests run: 921
        Disabled tests: 0
        Skipped tests: 0

Other information:
        Smoke test time: 13.89 seconds
        Main test time: 118.96 seconds
        Total time: 132.85 seconds
```

## ODBC TDVT

```
$ python -m tdvt.tdvt run exasol_odbc
Setting tdvt thread count to: 6
Testing exasol_odbc
thread setting in exasol_odbc.ini = 1
Starting smoke tests. Creating 1 worker threads.

Running exasol_odbc StaplesConnectionTestexasol_odbc 12

.
Finished exasol_odbc StaplesConnectionTestexasol_odbc 12

Running exasol_odbc CastCalcsConnectionTestexasol_odbc 12

.
Finished exasol_odbc CastCalcsConnectionTestexasol_odbc 12

2 smoke test(s) ran. 0 smoke tests disabled.
Smoke tests ran in 6.74 seconds.

Starting tests. Creating 1 worker threads.
Running exasol_odbc logical.calcs.exasol_odbc 1

...............................
Finished exasol_odbc logical.calcs.exasol_odbc 1

Running exasol_odbc logical.staples.exasol_odbc 2

..........................................
Finished exasol_odbc logical.staples.exasol_odbc 2

Running exasol_odbc logical.lod.exasol_odbc 3

...........................
Finished exasol_odbc logical.lod.exasol_odbc 3

Running exasol_odbc logical.union.exasol_odbc 4

.
Finished exasol_odbc logical.union.exasol_odbc 4

Running exasol_odbc expression.standard.exasol_odbc 5

...............................................................................................................................................................................................................
Finished exasol_odbc expression.standard.exasol_odbc 5

Running exasol_odbc expression.lod.exasol_odbc 6

.
Finished exasol_odbc expression.lod.exasol_odbc 6

Running exasol_odbc expression.staples.exasol_odbc 7

....
Finished exasol_odbc expression.staples.exasol_odbc 7

Running exasol_odbc expression.median.exasol_odbc 8

.
Finished exasol_odbc expression.median.exasol_odbc 8

Running exasol_odbc expression.percentile.exasol_odbc 9

.
Finished exasol_odbc expression.percentile.exasol_odbc 9

Running exasol_odbc calc_data.exasol_odbc 10

.
Finished exasol_odbc calc_data.exasol_odbc 10

Running exasol_odbc TestBadPassword.exasol_odbc 11

.
Finished exasol_odbc TestBadPassword.exasol_odbc 11


Test Count: 921 tests
        Passed tests: 921
        Failed tests: 0
        Tests run: 921
        Disabled tests: 0
        Skipped tests: 0

Other information:
        Smoke test time: 6.74 seconds
        Main test time: 84.3 seconds
        Total time: 91.04 seconds
```

2021-11-08 15:10 UTC, AnastasiiaSergienko reviewed
A few small findings :)

2021-11-09 08:13 UTC, AnastasiiaSergienko requested changes
Two more tiny findings

2021-11-09 08:13 UTC, AnastasiiaSergienko commented on doc/user_guide/user_guide.md
> +Download and install the latest JDBC driver for your operating system from the [download page](https://www.exasol.com/portal/display/DOWNLOAD/).
```suggestion
Download and install the latest ODBC driver for your operating system from the [Exasol download page](https://www.exasol.com/portal/display/DOWNLOAD/).
```

2021-11-09 08:13 UTC, AnastasiiaSergienko commented on doc/user_guide/user_guide.md
> +    "C:\Program Files\Tableau\Tableau 2021.3\bin\tableau.exe" -DDisableVerifyConnectorPluginSignature
Maybe the version placeholder is better? You can forget to change this when the new Tableau version is released

2021-11-09 09:04 UTC, AnastasiiaSergienko approved these changes

2021-11-09 12:41 UTC, merged